language: node_js
node_js:
  - '0.10'
env:
  global:
    # GOOGLE_USER
    - secure: YY57z+8ime6MbirPzTOMc80810bJ/l7/TQGIhGPxe8ZlqGYOCBIKMezDohBjCBmVH6BVfe7fAhXCIUT0zl+Uw/kyvDZkvzgr7DSjB/ufuzNVdCi4roVoF/j52YeBbzdCsQgxSC1IyTVZ9RoIBJ5suXj2+dvtNF8bd4brx63KfFw=
    # GOOGLE_PASSWORD
    - secure: hXhWFk9jQVcuj9qX5Db7hIWS5lWbrzr4PWqd5IUcXhBWaEboIHP3M7G6nUi+00m9CC99eD4D7mKIUr6cVVbM3qWcbtyn3ZYq9GOzrr8WeM//urQzkGpLoj+Fenx2WVFfS4JPBlXxvHcvOOAFMIFxci6Px11ucJXCtaqMfIsYy7U=
