exclude : ['README.rst', 'process.py', 'vendor/recline/index.html', 'vendor/recline/library.html']
safe: false

JB :
    analytics :
        provider : google
        google :
            tracking_id : 'UA-8271754-48'
